name: Run SonarQube analysis
on:
  workflow_call:
    secrets: 
      token:
        required: true
      host:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
   steps:
      - name: my-step
        run: echo "Sonar maintenance break!"
